/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_ROBOTCONTROL_ROBOT_CONTROL_PB_H_INCLUDED
#define PB_ROBOTCONTROL_ROBOT_CONTROL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RobotControl_ActivateController_ControllerType {
    RobotControl_ActivateController_ControllerType_DEACTIVATED = 0,
    RobotControl_ActivateController_ControllerType_NEURAL_NET = 1,
    RobotControl_ActivateController_ControllerType_PID = 2
} RobotControl_ActivateController_ControllerType;

/* Struct definitions */
typedef struct _RobotControl_NumbersArray {
    pb_callback_t values;
} RobotControl_NumbersArray;

typedef struct _RobotControl_ActivateController {
    RobotControl_ActivateController_ControllerType type;
} RobotControl_ActivateController;

typedef struct _RobotControl_Log {
    pb_callback_t msg;
    bool has_milliseconds_since_start;
    int32_t milliseconds_since_start;
} RobotControl_Log;

typedef struct _RobotControl_ModelEvaluationRequest {
    RobotControl_NumbersArray input_values;
} RobotControl_ModelEvaluationRequest;

typedef struct _RobotControl_ModelEvaluationResponse {
    RobotControl_NumbersArray output_values;
} RobotControl_ModelEvaluationResponse;

typedef struct _RobotControl_ModelUpdateRequest {
    int32_t param_id;
    int32_t param_start_offset;
    RobotControl_NumbersArray param_values;
} RobotControl_ModelUpdateRequest;


/* Helper constants for enums */
#define _RobotControl_ActivateController_ControllerType_MIN RobotControl_ActivateController_ControllerType_DEACTIVATED
#define _RobotControl_ActivateController_ControllerType_MAX RobotControl_ActivateController_ControllerType_PID
#define _RobotControl_ActivateController_ControllerType_ARRAYSIZE ((RobotControl_ActivateController_ControllerType)(RobotControl_ActivateController_ControllerType_PID+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RobotControl_ModelEvaluationRequest_init_default {RobotControl_NumbersArray_init_default}
#define RobotControl_ModelUpdateRequest_init_default {0, 0, RobotControl_NumbersArray_init_default}
#define RobotControl_ModelEvaluationResponse_init_default {RobotControl_NumbersArray_init_default}
#define RobotControl_Log_init_default            {{{NULL}, NULL}, false, 0}
#define RobotControl_NumbersArray_init_default   {{{NULL}, NULL}}
#define RobotControl_ActivateController_init_default {RobotControl_ActivateController_ControllerType_DEACTIVATED}
#define RobotControl_ModelEvaluationRequest_init_zero {RobotControl_NumbersArray_init_zero}
#define RobotControl_ModelUpdateRequest_init_zero {0, 0, RobotControl_NumbersArray_init_zero}
#define RobotControl_ModelEvaluationResponse_init_zero {RobotControl_NumbersArray_init_zero}
#define RobotControl_Log_init_zero               {{{NULL}, NULL}, false, 0}
#define RobotControl_NumbersArray_init_zero      {{{NULL}, NULL}}
#define RobotControl_ActivateController_init_zero {_RobotControl_ActivateController_ControllerType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define RobotControl_NumbersArray_values_tag     1
#define RobotControl_ActivateController_type_tag 2
#define RobotControl_Log_msg_tag                 1
#define RobotControl_Log_milliseconds_since_start_tag 2
#define RobotControl_ModelEvaluationRequest_input_values_tag 1
#define RobotControl_ModelEvaluationResponse_output_values_tag 1
#define RobotControl_ModelUpdateRequest_param_id_tag 1
#define RobotControl_ModelUpdateRequest_param_start_offset_tag 2
#define RobotControl_ModelUpdateRequest_param_values_tag 3

/* Struct field encoding specification for nanopb */
#define RobotControl_ModelEvaluationRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  input_values,      1)
#define RobotControl_ModelEvaluationRequest_CALLBACK NULL
#define RobotControl_ModelEvaluationRequest_DEFAULT NULL
#define RobotControl_ModelEvaluationRequest_input_values_MSGTYPE RobotControl_NumbersArray

#define RobotControl_ModelUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    param_id,          1) \
X(a, STATIC,   REQUIRED, INT32,    param_start_offset,   2) \
X(a, STATIC,   REQUIRED, MESSAGE,  param_values,      3)
#define RobotControl_ModelUpdateRequest_CALLBACK NULL
#define RobotControl_ModelUpdateRequest_DEFAULT NULL
#define RobotControl_ModelUpdateRequest_param_values_MSGTYPE RobotControl_NumbersArray

#define RobotControl_ModelEvaluationResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  output_values,     1)
#define RobotControl_ModelEvaluationResponse_CALLBACK NULL
#define RobotControl_ModelEvaluationResponse_DEFAULT NULL
#define RobotControl_ModelEvaluationResponse_output_values_MSGTYPE RobotControl_NumbersArray

#define RobotControl_Log_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   msg,               1) \
X(a, STATIC,   OPTIONAL, INT32,    milliseconds_since_start,   2)
#define RobotControl_Log_CALLBACK pb_default_field_callback
#define RobotControl_Log_DEFAULT NULL

#define RobotControl_NumbersArray_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, FLOAT,    values,            1)
#define RobotControl_NumbersArray_CALLBACK pb_default_field_callback
#define RobotControl_NumbersArray_DEFAULT NULL

#define RobotControl_ActivateController_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              2)
#define RobotControl_ActivateController_CALLBACK NULL
#define RobotControl_ActivateController_DEFAULT NULL

extern const pb_msgdesc_t RobotControl_ModelEvaluationRequest_msg;
extern const pb_msgdesc_t RobotControl_ModelUpdateRequest_msg;
extern const pb_msgdesc_t RobotControl_ModelEvaluationResponse_msg;
extern const pb_msgdesc_t RobotControl_Log_msg;
extern const pb_msgdesc_t RobotControl_NumbersArray_msg;
extern const pb_msgdesc_t RobotControl_ActivateController_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RobotControl_ModelEvaluationRequest_fields &RobotControl_ModelEvaluationRequest_msg
#define RobotControl_ModelUpdateRequest_fields &RobotControl_ModelUpdateRequest_msg
#define RobotControl_ModelEvaluationResponse_fields &RobotControl_ModelEvaluationResponse_msg
#define RobotControl_Log_fields &RobotControl_Log_msg
#define RobotControl_NumbersArray_fields &RobotControl_NumbersArray_msg
#define RobotControl_ActivateController_fields &RobotControl_ActivateController_msg

/* Maximum encoded size of messages (where known) */
/* RobotControl_ModelEvaluationRequest_size depends on runtime parameters */
/* RobotControl_ModelUpdateRequest_size depends on runtime parameters */
/* RobotControl_ModelEvaluationResponse_size depends on runtime parameters */
/* RobotControl_Log_size depends on runtime parameters */
/* RobotControl_NumbersArray_size depends on runtime parameters */
#define RobotControl_ActivateController_size     2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
