/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "robot_control.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RobotControl_ModelEvaluationRequest, RobotControl_ModelEvaluationRequest, AUTO)


PB_BIND(RobotControl_ModelUpdateRequest, RobotControl_ModelUpdateRequest, AUTO)


PB_BIND(RobotControl_ModelEvaluationResponse, RobotControl_ModelEvaluationResponse, AUTO)


PB_BIND(RobotControl_Log, RobotControl_Log, AUTO)


PB_BIND(RobotControl_NumbersArray, RobotControl_NumbersArray, AUTO)


PB_BIND(RobotControl_ActivateController, RobotControl_ActivateController, AUTO)




