/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_REMOTENETWORK_REMOTE_NETWORK_PB_H_INCLUDED
#define PB_REMOTENETWORK_REMOTE_NETWORK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RemoteNetwork_Log {
    char msg[128];
    bool has_milliseconds_since_start;
    int32_t milliseconds_since_start;
} RemoteNetwork_Log;

typedef struct _RemoteNetwork_NumbersArray {
    pb_size_t values_count;
    float values[128];
} RemoteNetwork_NumbersArray;

typedef struct _RemoteNetwork_ModelEvaluationRequest {
    RemoteNetwork_NumbersArray input_values;
} RemoteNetwork_ModelEvaluationRequest;

typedef struct _RemoteNetwork_ModelEvaluationResponse {
    RemoteNetwork_NumbersArray output_values;
} RemoteNetwork_ModelEvaluationResponse;

typedef struct _RemoteNetwork_ModelUpdateRequest {
    int32_t param_id;
    int32_t param_start_offset;
    RemoteNetwork_NumbersArray param_values;
} RemoteNetwork_ModelUpdateRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RemoteNetwork_ModelEvaluationRequest_init_default {RemoteNetwork_NumbersArray_init_default}
#define RemoteNetwork_ModelUpdateRequest_init_default {0, 0, RemoteNetwork_NumbersArray_init_default}
#define RemoteNetwork_ModelEvaluationResponse_init_default {RemoteNetwork_NumbersArray_init_default}
#define RemoteNetwork_Log_init_default           {"", false, 0}
#define RemoteNetwork_NumbersArray_init_default  {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define RemoteNetwork_ModelEvaluationRequest_init_zero {RemoteNetwork_NumbersArray_init_zero}
#define RemoteNetwork_ModelUpdateRequest_init_zero {0, 0, RemoteNetwork_NumbersArray_init_zero}
#define RemoteNetwork_ModelEvaluationResponse_init_zero {RemoteNetwork_NumbersArray_init_zero}
#define RemoteNetwork_Log_init_zero              {"", false, 0}
#define RemoteNetwork_NumbersArray_init_zero     {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define RemoteNetwork_Log_msg_tag                1
#define RemoteNetwork_Log_milliseconds_since_start_tag 2
#define RemoteNetwork_NumbersArray_values_tag    1
#define RemoteNetwork_ModelEvaluationRequest_input_values_tag 1
#define RemoteNetwork_ModelEvaluationResponse_output_values_tag 1
#define RemoteNetwork_ModelUpdateRequest_param_id_tag 1
#define RemoteNetwork_ModelUpdateRequest_param_start_offset_tag 2
#define RemoteNetwork_ModelUpdateRequest_param_values_tag 3

/* Struct field encoding specification for nanopb */
#define RemoteNetwork_ModelEvaluationRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  input_values,      1)
#define RemoteNetwork_ModelEvaluationRequest_CALLBACK NULL
#define RemoteNetwork_ModelEvaluationRequest_DEFAULT NULL
#define RemoteNetwork_ModelEvaluationRequest_input_values_MSGTYPE RemoteNetwork_NumbersArray

#define RemoteNetwork_ModelUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    param_id,          1) \
X(a, STATIC,   REQUIRED, INT32,    param_start_offset,   2) \
X(a, STATIC,   REQUIRED, MESSAGE,  param_values,      3)
#define RemoteNetwork_ModelUpdateRequest_CALLBACK NULL
#define RemoteNetwork_ModelUpdateRequest_DEFAULT NULL
#define RemoteNetwork_ModelUpdateRequest_param_values_MSGTYPE RemoteNetwork_NumbersArray

#define RemoteNetwork_ModelEvaluationResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  output_values,     1)
#define RemoteNetwork_ModelEvaluationResponse_CALLBACK NULL
#define RemoteNetwork_ModelEvaluationResponse_DEFAULT NULL
#define RemoteNetwork_ModelEvaluationResponse_output_values_MSGTYPE RemoteNetwork_NumbersArray

#define RemoteNetwork_Log_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   msg,               1) \
X(a, STATIC,   OPTIONAL, INT32,    milliseconds_since_start,   2)
#define RemoteNetwork_Log_CALLBACK NULL
#define RemoteNetwork_Log_DEFAULT NULL

#define RemoteNetwork_NumbersArray_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    values,            1)
#define RemoteNetwork_NumbersArray_CALLBACK NULL
#define RemoteNetwork_NumbersArray_DEFAULT NULL

extern const pb_msgdesc_t RemoteNetwork_ModelEvaluationRequest_msg;
extern const pb_msgdesc_t RemoteNetwork_ModelUpdateRequest_msg;
extern const pb_msgdesc_t RemoteNetwork_ModelEvaluationResponse_msg;
extern const pb_msgdesc_t RemoteNetwork_Log_msg;
extern const pb_msgdesc_t RemoteNetwork_NumbersArray_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RemoteNetwork_ModelEvaluationRequest_fields &RemoteNetwork_ModelEvaluationRequest_msg
#define RemoteNetwork_ModelUpdateRequest_fields &RemoteNetwork_ModelUpdateRequest_msg
#define RemoteNetwork_ModelEvaluationResponse_fields &RemoteNetwork_ModelEvaluationResponse_msg
#define RemoteNetwork_Log_fields &RemoteNetwork_Log_msg
#define RemoteNetwork_NumbersArray_fields &RemoteNetwork_NumbersArray_msg

/* Maximum encoded size of messages (where known) */
#define RemoteNetwork_ModelEvaluationRequest_size 643
#define RemoteNetwork_ModelUpdateRequest_size    665
#define RemoteNetwork_ModelEvaluationResponse_size 643
#define RemoteNetwork_Log_size                   141
#define RemoteNetwork_NumbersArray_size          640

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
