/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "remote_network.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RemoteNetwork_ModelEvaluationRequest, RemoteNetwork_ModelEvaluationRequest, 2)


PB_BIND(RemoteNetwork_ModelUpdateRequest, RemoteNetwork_ModelUpdateRequest, 2)


PB_BIND(RemoteNetwork_ModelEvaluationResponse, RemoteNetwork_ModelEvaluationResponse, 2)


PB_BIND(RemoteNetwork_Log, RemoteNetwork_Log, AUTO)


PB_BIND(RemoteNetwork_NumbersArray, RemoteNetwork_NumbersArray, 2)



