# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_network.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote_network.proto',
  package='RemoteNetwork',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14remote_network.proto\x12\rRemoteNetwork\"K\n\x16ModelEvaluationRequest\x12\x31\n\x0cinput_values\x18\x01 \x02(\x0b\x32\x1b.RemoteNetwork.NumbersArray\"u\n\x12ModelUpdateRequest\x12\x10\n\x08param_id\x18\x01 \x02(\x05\x12\x1a\n\x12param_start_offset\x18\x02 \x02(\x05\x12\x31\n\x0cparam_values\x18\x03 \x02(\x0b\x32\x1b.RemoteNetwork.NumbersArray\"M\n\x17ModelEvaluationResponse\x12\x32\n\routput_values\x18\x01 \x02(\x0b\x32\x1b.RemoteNetwork.NumbersArray\"4\n\x03Log\x12\x0b\n\x03msg\x18\x01 \x02(\t\x12 \n\x18milliseconds_since_start\x18\x02 \x01(\x05\"\"\n\x0cNumbersArray\x12\x12\n\x06values\x18\x01 \x03(\x02\x42\x02\x10\x01'
)




_MODELEVALUATIONREQUEST = _descriptor.Descriptor(
  name='ModelEvaluationRequest',
  full_name='RemoteNetwork.ModelEvaluationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_values', full_name='RemoteNetwork.ModelEvaluationRequest.input_values', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=114,
)


_MODELUPDATEREQUEST = _descriptor.Descriptor(
  name='ModelUpdateRequest',
  full_name='RemoteNetwork.ModelUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='param_id', full_name='RemoteNetwork.ModelUpdateRequest.param_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param_start_offset', full_name='RemoteNetwork.ModelUpdateRequest.param_start_offset', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param_values', full_name='RemoteNetwork.ModelUpdateRequest.param_values', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=233,
)


_MODELEVALUATIONRESPONSE = _descriptor.Descriptor(
  name='ModelEvaluationResponse',
  full_name='RemoteNetwork.ModelEvaluationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output_values', full_name='RemoteNetwork.ModelEvaluationResponse.output_values', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=312,
)


_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='RemoteNetwork.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='RemoteNetwork.Log.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='milliseconds_since_start', full_name='RemoteNetwork.Log.milliseconds_since_start', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=366,
)


_NUMBERSARRAY = _descriptor.Descriptor(
  name='NumbersArray',
  full_name='RemoteNetwork.NumbersArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='RemoteNetwork.NumbersArray.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=402,
)

_MODELEVALUATIONREQUEST.fields_by_name['input_values'].message_type = _NUMBERSARRAY
_MODELUPDATEREQUEST.fields_by_name['param_values'].message_type = _NUMBERSARRAY
_MODELEVALUATIONRESPONSE.fields_by_name['output_values'].message_type = _NUMBERSARRAY
DESCRIPTOR.message_types_by_name['ModelEvaluationRequest'] = _MODELEVALUATIONREQUEST
DESCRIPTOR.message_types_by_name['ModelUpdateRequest'] = _MODELUPDATEREQUEST
DESCRIPTOR.message_types_by_name['ModelEvaluationResponse'] = _MODELEVALUATIONRESPONSE
DESCRIPTOR.message_types_by_name['Log'] = _LOG
DESCRIPTOR.message_types_by_name['NumbersArray'] = _NUMBERSARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelEvaluationRequest = _reflection.GeneratedProtocolMessageType('ModelEvaluationRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELEVALUATIONREQUEST,
  '__module__' : 'remote_network_pb2'
  # @@protoc_insertion_point(class_scope:RemoteNetwork.ModelEvaluationRequest)
  })
_sym_db.RegisterMessage(ModelEvaluationRequest)

ModelUpdateRequest = _reflection.GeneratedProtocolMessageType('ModelUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELUPDATEREQUEST,
  '__module__' : 'remote_network_pb2'
  # @@protoc_insertion_point(class_scope:RemoteNetwork.ModelUpdateRequest)
  })
_sym_db.RegisterMessage(ModelUpdateRequest)

ModelEvaluationResponse = _reflection.GeneratedProtocolMessageType('ModelEvaluationResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELEVALUATIONRESPONSE,
  '__module__' : 'remote_network_pb2'
  # @@protoc_insertion_point(class_scope:RemoteNetwork.ModelEvaluationResponse)
  })
_sym_db.RegisterMessage(ModelEvaluationResponse)

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), {
  'DESCRIPTOR' : _LOG,
  '__module__' : 'remote_network_pb2'
  # @@protoc_insertion_point(class_scope:RemoteNetwork.Log)
  })
_sym_db.RegisterMessage(Log)

NumbersArray = _reflection.GeneratedProtocolMessageType('NumbersArray', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERSARRAY,
  '__module__' : 'remote_network_pb2'
  # @@protoc_insertion_point(class_scope:RemoteNetwork.NumbersArray)
  })
_sym_db.RegisterMessage(NumbersArray)


_NUMBERSARRAY.fields_by_name['values']._options = None
# @@protoc_insertion_point(module_scope)
