# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_control.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_control.proto',
  package='RobotControl',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13robot_control.proto\x12\x0cRobotControl\"J\n\x16ModelEvaluationRequest\x12\x30\n\x0cinput_values\x18\x01 \x02(\x0b\x32\x1a.RobotControl.NumbersArray\"t\n\x12ModelUpdateRequest\x12\x10\n\x08param_id\x18\x01 \x02(\x05\x12\x1a\n\x12param_start_offset\x18\x02 \x02(\x05\x12\x30\n\x0cparam_values\x18\x03 \x02(\x0b\x32\x1a.RobotControl.NumbersArray\"L\n\x17ModelEvaluationResponse\x12\x31\n\routput_values\x18\x01 \x02(\x0b\x32\x1a.RobotControl.NumbersArray\"4\n\x03Log\x12\x0b\n\x03msg\x18\x01 \x02(\t\x12 \n\x18milliseconds_since_start\x18\x02 \x01(\x05\"\"\n\x0cNumbersArray\x12\x12\n\x06values\x18\x01 \x03(\x02\x42\x02\x10\x01\"\xaf\x01\n\x12\x41\x63tivateController\x12\x11\n\x06run_id\x18\x01 \x01(\x05:\x01\x30\x12J\n\x04type\x18\x02 \x02(\x0e\x32/.RobotControl.ActivateController.ControllerType:\x0b\x44\x45\x41\x43TIVATED\":\n\x0e\x43ontrollerType\x12\x0f\n\x0b\x44\x45\x41\x43TIVATED\x10\x00\x12\x0e\n\nNEURAL_NET\x10\x01\x12\x07\n\x03PID\x10\x02'
)



_ACTIVATECONTROLLER_CONTROLLERTYPE = _descriptor.EnumDescriptor(
  name='ControllerType',
  full_name='RobotControl.ActivateController.ControllerType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEACTIVATED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEURAL_NET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PID', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=517,
  serialized_end=575,
)
_sym_db.RegisterEnumDescriptor(_ACTIVATECONTROLLER_CONTROLLERTYPE)


_MODELEVALUATIONREQUEST = _descriptor.Descriptor(
  name='ModelEvaluationRequest',
  full_name='RobotControl.ModelEvaluationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_values', full_name='RobotControl.ModelEvaluationRequest.input_values', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=111,
)


_MODELUPDATEREQUEST = _descriptor.Descriptor(
  name='ModelUpdateRequest',
  full_name='RobotControl.ModelUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='param_id', full_name='RobotControl.ModelUpdateRequest.param_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param_start_offset', full_name='RobotControl.ModelUpdateRequest.param_start_offset', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param_values', full_name='RobotControl.ModelUpdateRequest.param_values', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=229,
)


_MODELEVALUATIONRESPONSE = _descriptor.Descriptor(
  name='ModelEvaluationResponse',
  full_name='RobotControl.ModelEvaluationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output_values', full_name='RobotControl.ModelEvaluationResponse.output_values', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=307,
)


_LOG = _descriptor.Descriptor(
  name='Log',
  full_name='RobotControl.Log',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='RobotControl.Log.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='milliseconds_since_start', full_name='RobotControl.Log.milliseconds_since_start', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=361,
)


_NUMBERSARRAY = _descriptor.Descriptor(
  name='NumbersArray',
  full_name='RobotControl.NumbersArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='RobotControl.NumbersArray.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=397,
)


_ACTIVATECONTROLLER = _descriptor.Descriptor(
  name='ActivateController',
  full_name='RobotControl.ActivateController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='run_id', full_name='RobotControl.ActivateController.run_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='RobotControl.ActivateController.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTIVATECONTROLLER_CONTROLLERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=575,
)

_MODELEVALUATIONREQUEST.fields_by_name['input_values'].message_type = _NUMBERSARRAY
_MODELUPDATEREQUEST.fields_by_name['param_values'].message_type = _NUMBERSARRAY
_MODELEVALUATIONRESPONSE.fields_by_name['output_values'].message_type = _NUMBERSARRAY
_ACTIVATECONTROLLER.fields_by_name['type'].enum_type = _ACTIVATECONTROLLER_CONTROLLERTYPE
_ACTIVATECONTROLLER_CONTROLLERTYPE.containing_type = _ACTIVATECONTROLLER
DESCRIPTOR.message_types_by_name['ModelEvaluationRequest'] = _MODELEVALUATIONREQUEST
DESCRIPTOR.message_types_by_name['ModelUpdateRequest'] = _MODELUPDATEREQUEST
DESCRIPTOR.message_types_by_name['ModelEvaluationResponse'] = _MODELEVALUATIONRESPONSE
DESCRIPTOR.message_types_by_name['Log'] = _LOG
DESCRIPTOR.message_types_by_name['NumbersArray'] = _NUMBERSARRAY
DESCRIPTOR.message_types_by_name['ActivateController'] = _ACTIVATECONTROLLER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelEvaluationRequest = _reflection.GeneratedProtocolMessageType('ModelEvaluationRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELEVALUATIONREQUEST,
  '__module__' : 'robot_control_pb2'
  # @@protoc_insertion_point(class_scope:RobotControl.ModelEvaluationRequest)
  })
_sym_db.RegisterMessage(ModelEvaluationRequest)

ModelUpdateRequest = _reflection.GeneratedProtocolMessageType('ModelUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELUPDATEREQUEST,
  '__module__' : 'robot_control_pb2'
  # @@protoc_insertion_point(class_scope:RobotControl.ModelUpdateRequest)
  })
_sym_db.RegisterMessage(ModelUpdateRequest)

ModelEvaluationResponse = _reflection.GeneratedProtocolMessageType('ModelEvaluationResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELEVALUATIONRESPONSE,
  '__module__' : 'robot_control_pb2'
  # @@protoc_insertion_point(class_scope:RobotControl.ModelEvaluationResponse)
  })
_sym_db.RegisterMessage(ModelEvaluationResponse)

Log = _reflection.GeneratedProtocolMessageType('Log', (_message.Message,), {
  'DESCRIPTOR' : _LOG,
  '__module__' : 'robot_control_pb2'
  # @@protoc_insertion_point(class_scope:RobotControl.Log)
  })
_sym_db.RegisterMessage(Log)

NumbersArray = _reflection.GeneratedProtocolMessageType('NumbersArray', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERSARRAY,
  '__module__' : 'robot_control_pb2'
  # @@protoc_insertion_point(class_scope:RobotControl.NumbersArray)
  })
_sym_db.RegisterMessage(NumbersArray)

ActivateController = _reflection.GeneratedProtocolMessageType('ActivateController', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATECONTROLLER,
  '__module__' : 'robot_control_pb2'
  # @@protoc_insertion_point(class_scope:RobotControl.ActivateController)
  })
_sym_db.RegisterMessage(ActivateController)


_NUMBERSARRAY.fields_by_name['values']._options = None
# @@protoc_insertion_point(module_scope)
